# Configuration file for scenario theta 
#p1_setting.append(sim._model.getLinkResult('1', tkai.LinkResults.setting.value))
#p2_setting.append(sim._model.getLinkResult('2', tkai.LinkResults.setting.value))
#
#p1_depth.append(p1.depth)
#p2_depth.append(p2.depth)
#
#p1_fld.append(p1.flooding)
#p2_fld.append(p1.flooding)
#
#l8_flow.append(l8.flow)
# name of scearnio 
name: theta
# state definitions
states:
        - !!python/tuple 
          - P1
          - depthN
        - !!python/tuple
          - P2
          - depthN
        - !!python/tuple
          - "1"
          - setting
        - !!python/tuple
          - "2"
          - setting
# Action space 
action_space:
        - "1"
        - "2"
# Performance Targets
performance_targets:
        - !!python/tuple
          - "8"
          - flow
        - !!python/tuple
          - P1
          - flooding
        - !!python/tuple
          - P2
          - flooding
